# Generated by Django 5.2.3 on 2026-01-14 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0005_visitor_induction_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InductionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('marks', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InductionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='induction.inductionquestion')),
            ],
        ),
        migrations.CreateModel(
            name='InductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_required', 'Not required'), ('pending_video', 'Pending video'), ('video_completed', 'Video completed'), ('quiz_in_progress', 'Quiz in progress'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending_video', max_length=30)),
                ('video_started_at', models.DateTimeField(blank=True, null=True)),
                ('video_completed_at', models.DateTimeField(blank=True, null=True)),
                ('watched_seconds', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='induction', to='userauth.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='InductionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts_list', to='induction.inductionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='InductionAttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='induction.inductionattempt')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='induction.inductionoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='induction.inductionquestion')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
