# Generated by Django 5.2.3 on 2025-11-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_user_username_alter_visitor_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
