# Generated by Django 5.2.3 on 2025-11-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_visitor_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='visit_date',
            new_name='scheduled_date',
        ),
    ]
