# Generated by Django 5.2.3 on 2026-01-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_rename_visit_date_visitor_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='induction_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='induction_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='induction_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='induction_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='induction_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending_video', 'Pending Video'), ('video_completed', 'Video Completed'), ('quiz_in_progress', 'Quiz In Progress'), ('passed', 'Passed'), ('failed', 'Failed')], default='not_required', max_length=30),
        ),
    ]
